- name: "hello world playbook"
  hosts: localhost
  vars_files:
    - ../files/vault.yml
  tasks:

    - name: Print Message from local Vault
      ansible.builtin.debug:
        msg: "vault secret: {{ vault_secret }}"

    - name: Print Message from HashiCorp Vault
      # Note: The API path for this value is: "/v1/secret/data/hashi_secret"
      ansible.builtin.debug:
        msg: >-
          {{
            lookup(
              'community.hashi_vault.hashi_vault',
              'secret=secret/data/hashi_secret:message',
              namespace='admin'
            )
          }}

